# Generated by Django 5.2.4 on 2025-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, default='Neutral', max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='ai_analysis',
            field=models.TextField(default='No analysis'),
        ),
    ]
